FireSale/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('fire_sale.urls')),
    path('admin/', admin.site.urls),
    path('user/', include('user.urls')),
    path('listing/', include('listing.urls')),
    path('checkout/', include('checkout.urls')),
    path('offer/', include('offer.urls'))
]

listing/urls.py
from django.urls import path
import offer.views
from . import views

urlpatterns = [
    # http://localhost:8000/listing
    path('', views.get_all_listings, name="listings"),
    path('<int:listing_id>/details', views.get_listing_by_id, name="listing-details"),
    path('add', views.add_listing, name="add-listing"),
    path('<int:listing_id>/remove', views.remove_listing, name="remove-listing"),
    path('<int:listing_id>/update', views.update_listing, name="update-listing"),
    path('<int:listing_id>/make_offer', offer.views.make_offer, name="make-offer")
]

user/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
import listing.views
import checkout.views
import offer.views
from . import views

urlpatterns = [
    # http://localhost:8000/user

    path('<int:user_id>/listings', listing.views.get_user_listings, name='user-listings'),
    path('register', views.register, name='register'),
    path('login', LoginView.as_view(template_name='user/login.html'), name='login'),
    path('logout', LogoutView.as_view(next_page='login'), name='logout'),
    path('<int:user_id>/profile', views.get_profile, name='user-profile'),
    path('profile', views.get_profile, name='my-profile'),
    path('edit_profile', views.edit_profile, name='edit-profile'),
    path('<int:buyer_id>/offers_made', offer.views.get_offers_by_buyer, name='offers-made'),
    path('<int:user_id>/ratings', views.get_user_ratings, name='user-ratings'),
    path('<int:to_user_id>/send_message', views.send_message, name='send-message'),
    path('send_message', views.send_message, name='send-message'),
    path('<int:user_id>/messages', views.get_message_chain, name='message-chain'),
    path('messages', views.get_user_message_chains, name='messages'),  # TODO: Is this needed?
    path('message/<int:message_id>', views.get_message_by_id, name='single-message'),
    path('<int:user_id>/purchases', checkout.views.get_user_purchases, name='user-purchases'),
    path('notifications', views.get_user_notifications, name='user-notifications'),
    path('notification/<int:notification_id>', views.get_notification_by_id, name='notification-details')
]

listing/models.py
from django.db import models
from django.contrib.auth.models import User


class Condition(models.Model):
    condition_text = models.CharField(max_length=255)

    def __str__(self):
        return self.condition_text


class Listing(models.Model):
    name = models.CharField(max_length=255)
    description = models.CharField(max_length=255, blank=True)
    seller = models.ForeignKey(User, on_delete=models.CASCADE)
    condition = models.ForeignKey(Condition, on_delete=models.SET_DEFAULT, default=1)
    listed = models.DateTimeField()
    available = models.BooleanField(default=True)
    purchased = models.BooleanField(default=False)


class ListingImage(models.Model):
    image = models.CharField(max_length=9999)
    listing = models.ForeignKey(Listing, on_delete=models.CASCADE)

offer/models.py
from django.core.validators import MinValueValidator
from django.db import models
from listing.models import Listing
from django.contrib.auth.models import User

# Create your models here.


class Offer(models.Model):
    listing = models.ForeignKey(Listing, on_delete=models.CASCADE)
    buyer = models.ForeignKey(User, on_delete=models.CASCADE)
    amount = models.IntegerField(validators=[MinValueValidator(0)])
    placed = models.DateTimeField()
    accepted = models.BooleanField(default=False)

listing/forms/listing_form.py
from django.forms import ModelForm, widgets
from django import forms
from listing.models import Listing


class ListingCreateForm(ModelForm):
    image = forms.CharField(required=True, widget=forms.TextInput(attrs={'class': 'form-control'}))

    class Meta:
        model = Listing
        exclude = ['id', 'seller', 'listed', 'available', 'purchased']
        widgets = {
            'name': widgets.TextInput(attrs={'class': 'form-control'}),
            'description': widgets.TextInput(attrs={'class': 'form-control'}),
            'condition': widgets.Select(attrs={'class': 'form-control'}),
        }


class ListingUpdateForm(ModelForm):
    class Meta:
        model = Listing
        exclude = ['id', 'seller', 'listed', 'available', 'purchased']
        widgets = {
            'name': widgets.TextInput(attrs={'class': 'form-control'}),
            'description': widgets.TextInput(attrs={'class': 'form-control'}),
            'condition': widgets.Select(attrs={'class': 'form-control'})
        }

listing/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.mail import message
from django.core.paginator import Paginator
from django.db.models import Q, Max
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.models import User
from django.http import JsonResponse
from offer.models import Offer
from listing.models import Listing, ListingImage
from listing.forms.listing_form import ListingCreateForm, ListingUpdateForm
import datetime
from listing.helper_functions import *

def get_listing_by_id(request, listing_id):
    """This view gives a detailed look at a specific listing.
    From this view a user can:
    see all info a seller has provided about a listing,
    see related products,
    see all offers made on the listing and make an offer themselves.
    If viewing their own listing a user can access options to edit or remove the listing
    and accept or decline offers.
"""
    listing = get_object_or_404(Listing, pk=listing_id)
    offers = Offer.objects.all().filter(listing_id=listing_id).order_by('-amount')
    paginator = Paginator(offers, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    list_of_listings = Listing.objects.all().filter(available=True).exclude(pk=listing_id)
    #mrp = most_related_products(listing, list_of_listings)
    #mrp = Listing.objects.filter(id__in=mrp)
    mrp = listing_relatedness_v2(listing)
    return render(request, 'listing/listingdetails.html', {
        'listing': listing,
        'mrp': mrp,
        'page_obj': page_obj
    })

def get_all_listings(request):
    """This view lets a user see all listings optionally filtered by a search string
    or sorted by name, price or listed date."""
    listings = Listing.objects.all().filter(available=True, purchased=False)

    if 'search_filter' in request.GET:
        search_filter = request.GET['search_filter']
        listings = listings.filter(Q(name__icontains=search_filter)|Q(description__icontains=search_filter))
    if 'sort' in request.GET:
        sort = request.GET['sort']
        if sort == 'name':
            listings = listings.order_by('name')
        elif sort == 'price':
            max_offer_by_listing = Offer.objects.all().values('listing_id').annotate(Max('amount')).order_by('amount__max')
            listing_ids = []
            for listing in max_offer_by_listing:
                listing_ids.append(listing['listing_id'])
            listings = Listing.objects.filter(id__in=listing_ids)
            listings = dict([(listing.id, listing) for listing in listings])
            listings = [listings[id] for id in listing_ids]
        elif sort == 'datetime':
            listings = listings.order_by('-listed')

    paginator = Paginator(listings, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request, 'listing/listings.html', {
        'page_obj': page_obj})


def get_user_listings(request, user_id):
    """This view lets the user see all listings posted by a specific user.
    In the next iteration of FireSale, this view should be updated to function similarly to
    get_all_listings.
    Another option would be to provide the user_id as an optional attribute to filter get_all_listings by"""
    listings = Listing.objects.all().filter(seller_id=user_id)
    listings_and_highest_offer = []
    for listing in listings:
        offer = Offer.objects.all().filter(listing_id=listing.id).order_by('-amount').first()
        listings_and_highest_offer.append([listing,offer])
    paginator = Paginator(listings_and_highest_offer, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request, 'listing/user_listings.html', {
        'page_obj': page_obj,
        'seller': get_object_or_404(User, pk=user_id)})


def add_listing(request):
    """This view lets a user add a listing"""
    if request.method == 'POST':
        form = ListingCreateForm(data=request.POST)
        if form.is_valid():
            listing = form.save(commit=False)
            listing.seller = get_object_or_404(User, pk=request.user.id)
            listing.listed = datetime.datetime.now()
            listing.available = True
            listing.save()
            listing_image = ListingImage(image=request.POST['image'], listing=listing)
            listing_image.save()
            messages.success(request, 'Listing added!')
            return redirect('listing-details', listing_id=listing.id)
        else:
            messages.error(request, 'Listing could not be added')
            return redirect('add-listing')
    else:
        form = ListingCreateForm()
    return render(request, 'listing/add_listing.html', {
        'form': form
    })


def remove_listing(request, listing_id):
    """This view lets the user remove their listing."""
    listing = get_object_or_404(Listing, pk=listing_id)
    listing.delete()
    messages.success(request, 'Listing removed!')
    return redirect('listings')


def update_listing(request, listing_id):
    """This listing lets a user update information for a listing they have added."""
    instance = get_object_or_404(Listing, pk=listing_id)
    if request.method == 'POST':
        form = ListingUpdateForm(data=request.POST, instance=instance)
        if form.is_valid() and instance.seller == request.user:
            listing = form.save(commit=False)
            listing.seller = get_object_or_404(User, pk=request.user.id)
            listing.listed = datetime.datetime.now()
            listing.available = True
            listing.save()
            messages.success(request, 'Listing updated!')
            return redirect('listing-details', listing.id)
        else:
            messages.error(request, 'Listing could not be updated')
            return redirect('listing-details', listing_id)
    else:
        form = ListingUpdateForm(instance=instance)
        return render(request, 'listing/update_listing.html', {
            'form': form,
            'listing_id': listing_id
        })

templates/listing/add_listing.html
{% extends "base.html" %}
{% block content %}
{#    Template to add a listing #}
    <form class="form form-horizontal" action="{% url 'add-listing' %}" method="post">
        {% csrf_token %}
        {{ form }}
    <input type="submit" value="Add Listing" class="btn btn-primary pull-right" style="clear:both; margin: 10px 0" />
    </form>
{% endblock %}

templates/listing/listing_list.html
{% block content %}
    <a href="{% url 'add-listing' %}" class="block btn btn-primary float-end">Add listing</a>
    <h1 class="red">Listings</h1>

    <div class="listings">
        {% for listing_and_offer in page_obj %}
{#            Displays an instance of a listing for every non-sold listing in the database#}
            {%  include 'listing/single_listing.html' with listing=listing_and_offer.0 offer=listing_and_offer.1%}
        {% endfor %}
    </div>

    {% include 'pagination.html' %}
{% endblock %}

templates/listing/listingdetails.html
{% extends 'base.html' %}
{%  block content %}
    <div class="offers">
            <h1>{{  listing.name }}</h1>
            <div id="singlelisting">
{#            Displays a detailed description of a specific listing #}
                {% for listing_image in listing.listingimage_set.all %}
                    <img src="{{ listing_image.image }}" class="listing-img" height="200px" width="200px"/>
                {% endfor %}
                <p> {{ listing.description }}</p>
                    <h5>Seller</h5>
                {% include 'user/tiny_user.html' with user=listing.seller %}
                <h5>Condition</h5>
                <p>{{ listing.condition }}</p>
                <h5>Listed</h5>
                <p>{{ listing.listed }}</p>
                <h5>Top offer</h5>
                <p>{% with offers=listing.offer_set.all|dictsortreversed:"amount" %} {{ offers.0.amount }} kr{% endwith %}</p>
                {% if request.user.is_authenticated %}
                {% if request.user.id == listing.seller.id%}

{#                    If the current user is the listing seller #}
{#                    the options to madify or remove the listing are present  #}

                    <a href="{% url 'remove-listing' listing.id %}" class="block btn btn-danger">Remove listing</a>
                    <a href="{% url 'update-listing' listing.id %}" class="block btn btn-info">Update listing</a>
                {% else %}

{#                    If the user is not the listing seller #}
{#                    the only option on the listing is to make an offer on it#}

                    <a href="{% url 'make-offer' listing.id %}" class="block btn btn-success">Make Offer</a>
                {% endif %}
                {% endif %}
        </div>
            <h2>Related products</h2>
        <div class="tiny_listing_list">
            {% for listing in mrp%}
{#           Displays all related listings#}
                {% include 'listing/single_tiny_listing.html' with listing=listing offer=1%}
            {% endfor %}
{#           Gets all the listing offers#}
            {%  include 'offer/offer_list.html' with page_obj=page_obj user=request.user%}</div>
    </div>
{% endblock %}

templates/listing/listings.html
{%  extends 'base.html' %}

{% block content %}
<form style="vertical-align: center" action="{% url 'listings' %}">
    <span>Sort by:</span>
    <select class="sort-by" name="sort">
          <option class="dropdown-item">Name</option>
          <option value="price">Lowest price</option>
          <option value="datetime"><p class="text">Newest</p></option>
          <input class="btn btn-primary" type="submit" value="Sort">
    </select>
  </form>
    <h1 class="red">Listings
        {% if request.GET.search_filter is not None %}
            results for {{ request.GET.search_filter }}
        {% endif %}</h1>
    <div class="listings">
        {% for listing in page_obj %}
{#            Displays all listings#}
            {% with offers=listing.offer_set.all|dictsortreversed:"amount" %}
{#            Gets the highest amount for each listing and displays it#}
            {% include 'listing/single_listing.html' with listing=listing offer=offers.0 %}
            {% endwith %}
        {% endfor %}
    </div>
    {% include 'pagination.html' %}
{% endblock %}

templates/listing/single_listing.html
{#Layout for a single listing#}
<a href="/listing/{{ listing.id }}/details">
    <div class="d-flex flex-row" id="singlelisting">
        <img class="listing-img" src="{{ listing.listingimage_set.first.image }}" height="200px" width="200px"/>
        <div class="listing-details">
            <h3>{{  listing.name }}</h3>
                {% if listing.available %}<h4>{% with offers=listing.offer_set.all|dictsortreversed:"amount" %} {% if offers.0 == None %} No offers yet {% else %}Top offer: {{ offers.0.amount }} kr{% endif %}{% endwith %}</h4>{% endif %}
            <p>{{ listing.description }}</p>
        </div>
    </div>
</a>

templates/listing/single_tiny_listing.html
{#Layout for a single 'tiny listing' #}
{#A tiny listing is used to represent related listings#}
<a href="{% url 'listing-details' listing.id%}">
    <div class="tiny-listing">
        <img class="img-float" src="{{ listing.listingimage_set.first.image }}"/>
        <div class="listing-details">
            <h4>{{  listing.name }}</h4>
        </div>
</div>
</a>

templates/listing/update_listing.html
{#Layout for updating a listing#}
{% extends "base.html" %}
{% block content %}
    <form class="form form-horizontal" action="{% url 'update-listing' listing_id%}" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Update Listing" class="btn btn-primary pull-right" style="clear:both; margin: 10px 0" />
    </form>
{% endblock %}

templates/listing/user_listings.html
{%  extends 'base.html' %}

{% block content %}
{#    Shows a users' listings#}
    <h1>
        {% if seller == user %}
{#            If the owner of the listing is the current user#}
            Your
        {% else %}
{#            If the owner of the listing is not the current user#}
            {{ seller }}'s
        {% endif %}
        listings:</h1>
    <div class="listings">
        {% for listing_and_offer in page_obj %}
            {%  include 'listing/single_listing.html' with listing=listing_and_offer.0 offer=listing_and_offer.1%}
        {% endfor %}
    </div>
    {% include 'pagination.html' %}
{% endblock %}